// harness/omp/manifest.ts — the oh-my-pi (omp) distribution row.
//
// Projects the harness-neutral core/ tree into dist/omp/.omp/, plus omp's
// authored shell surfaces and emit()-generated content (commands/, RULES.md).
//
// omp specifics vs Claude:
//   - token → .omp
//   - rules/ → aidlc-common/rules/ (omp nests rules inside aidlc-common so the
//     engine can compile them directly; the rulesRename "aidlc-common/rules"
//     makes prose substitution rewrite ".omp/rules/" → ".omp/aidlc-common/rules/"
//     and points the runtime's rules-subdir seam at the right location)
//   - hooks/ is AUTHORED (not core): omp requires hooks/pre/ and hooks/post/
//     subdirectory structure, which forces a different relative import path
//     (../../tools/ vs core's ../tools/). All 10 hooks are in harnessFiles with
//     the corrected paths.
//   - The orchestrator is a custom tool (aidlc-orchestrate/index.ts), not just
//     a Bash script. It ships as a harnessFile inside tools/.
//   - commands/ is EMITTED: one slash command per stage, per scope, plus utility
//     commands — generated by emit() from the compiled stage graph.
//   - RULES.md is EMITTED: the merged rule prose written by emit() from the
//     rule files so omp can inject it as always-apply context.
//   - AGENTS.md lands at the PROJECT ROOT (dist/omp/AGENTS.md).
//   - Session skills ship in-tree under skills/ (same as Claude/Kiro).

import type { HarnessManifest } from "../../scripts/manifest-types.ts";
import emit from "./emit.ts";
import onboardingFills from "./onboarding.fills.ts";

const manifest: HarnessManifest = {
  name: "omp",
  harnessDir: ".omp",

  // Core projection. rules/ maps to aidlc-common/rules/ (see rulesRename).
  // hooks/ is NOT in coreDirs — omp hooks are all harnessFiles with corrected
  // relative import paths for the hooks/pre/ and hooks/post/ placement.
  coreDirs: [
    { src: "tools", dst: "tools" },
    { src: "aidlc-common", dst: "aidlc-common" },
    { src: "knowledge", dst: "knowledge" },
    { src: "rules", dst: "aidlc-common/rules" },
    { src: "sensors", dst: "sensors" },
    { src: "scopes", dst: "scopes" },
    { src: "agents", dst: "agents" },
    // No hooks/ — omp hooks are authored in harness/omp/hooks/ with ../../tools/ paths.
    { src: "skills/aidlc-session-cost", dst: "skills/aidlc-session-cost" },
    { src: "skills/aidlc-replay", dst: "skills/aidlc-replay" },
    { src: "skills/aidlc-outcomes-pack", dst: "skills/aidlc-outcomes-pack" },
  ],

  // Authored omp shell surfaces.
  harnessFiles: [
    // Orchestrator skill + question-rendering annex
    { src: "skills/aidlc/SKILL.md", dst: "skills/aidlc/SKILL.md" },
    { src: "skills/aidlc/question-rendering.md", dst: "skills/aidlc/question-rendering.md" },
    // omp-specific hook library (shared helpers for the pre/post hooks)
    { src: "hooks/aidlc-omp-hook-lib.ts", dst: "hooks/aidlc-omp-hook-lib.ts" },
    { src: "hooks/aidlc-omp-hooks.d.ts", dst: "hooks/aidlc-omp-hooks.d.ts" },
    // Pre-hooks (core hooks adapted with ../../tools/ import paths)
    { src: "hooks/pre/aidlc-audit-logger.ts", dst: "hooks/pre/aidlc-audit-logger.ts" },
    { src: "hooks/pre/aidlc-log-subagent.ts", dst: "hooks/pre/aidlc-log-subagent.ts" },
    { src: "hooks/pre/aidlc-runtime-compile.ts", dst: "hooks/pre/aidlc-runtime-compile.ts" },
    { src: "hooks/pre/aidlc-sensor-fire.ts", dst: "hooks/pre/aidlc-sensor-fire.ts" },
    { src: "hooks/pre/aidlc-session-end.ts", dst: "hooks/pre/aidlc-session-end.ts" },
    { src: "hooks/pre/aidlc-session-start.ts", dst: "hooks/pre/aidlc-session-start.ts" },
    { src: "hooks/pre/aidlc-stop.ts", dst: "hooks/pre/aidlc-stop.ts" },
    { src: "hooks/pre/aidlc-sync-statusline.ts", dst: "hooks/pre/aidlc-sync-statusline.ts" },
    { src: "hooks/pre/aidlc-validate-state.ts", dst: "hooks/pre/aidlc-validate-state.ts" },
    // Post-hook (statusline, fired after each turn)
    { src: "hooks/post/aidlc-statusline.ts", dst: "hooks/post/aidlc-statusline.ts" },
    // Custom tool wrapper (exposes aidlc_orchestrate as an omp custom tool)
    { src: "tools/aidlc-orchestrate/index.ts", dst: "tools/aidlc-orchestrate/index.ts" },
    // System-prompt tail injected by omp into every session
    { src: "APPEND_SYSTEM.md", dst: "APPEND_SYSTEM.md" },
    // Placeholder directories for project-specific omp rules and TTSR guards
    { src: "rules/README.md", dst: "rules/README.md" },
    { src: "ttsr/README.md", dst: "ttsr/README.md" },
  ],

  // AGENTS.md rendered at the project root (beside .omp/, not inside it).
  onboarding: { dst: "AGENTS.md", projectRoot: true, fills: onboardingFills },

  // rules/ → aidlc-common/rules/ in both the filesystem (coreDirs dst above)
  // and in prose substitution. applyRulesRename rewrites ".omp/rules/" →
  // ".omp/aidlc-common/rules/" in all copied .md files. The harness.json written
  // by writeHarnessData carries rulesSubdir = "aidlc-common/rules" so the runtime
  // tools (aidlc-graph.ts, aidlc-lib.ts) resolve rule files correctly.
  rulesRename: "aidlc-common/rules",

  // Authored files inside otherwise-generated or mixed directories:
  //   hooks/      — entirely harness-authored (no core hooks mapped here)
  //   tools/aidlc-orchestrate/ — harness-authored custom tool inside core tools/
  //   APPEND_SYSTEM.md, RULES.md — harness-authored / emit-generated at harness root
  //   rules/README.md, ttsr/README.md — harness-authored placeholder dirs
  authoredExempt: [
    /^hooks\//,
    /^tools\/aidlc-orchestrate\//,
    /^APPEND_SYSTEM\.md$/,
    /^RULES\.md$/,
    /^rules\/README\.md$/,
    /^ttsr\/README\.md$/,
  ],

  emit,
};

export default manifest;
