#!/usr/bin/env bun
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

export const MARKDOWN_PARSER_BUN_VERSION = "1.3.14";
const ROOT = resolve(import.meta.dir, "..");
const VENDOR = join(ROOT, "core/tools/vendor");

interface PackageNotice {
  name: string;
  version: string;
  license: string;
  text: string;
}

export async function vendorMarkdownParser(output = join(VENDOR, "markdown-parser.js")): Promise<void> {
  if (Bun.version !== MARKDOWN_PARSER_BUN_VERSION) {
    throw new Error(`Markdown parser vendoring requires Bun ${MARKDOWN_PARSER_BUN_VERSION}; found ${Bun.version}. Refusing to write the bundle.`);
  }
  const rootPackage = JSON.parse(readFileSync(join(ROOT, "package.json"), "utf8"));
  if (rootPackage.packageManager !== `bun@${MARKDOWN_PARSER_BUN_VERSION}`) {
    throw new Error("The Markdown parser Bun pin must match package.json packageManager.");
  }
  const scratch = mkdtempSync(join(ROOT, ".markdown-parser-"));
  try {
    const entry = join(scratch, "entry.ts");
    writeFileSync(entry, [
      'export { parse, preprocess, postprocess } from "micromark";',
      'export { gfm } from "micromark-extension-gfm";',
      'export { normalizeIdentifier } from "micromark-util-normalize-identifier";',
      "",
    ].join("\n"));
    const result = await Bun.build({
      entrypoints: [entry],
      target: "bun",
      format: "esm",
      minify: true,
      metafile: true,
    });
    if (!result.success) throw new AggregateError(result.logs, "Markdown parser bundle failed");
    if (result.outputs.length !== 1 || !result.metafile) {
      throw new Error("Expected one self-contained Markdown parser bundle with build metadata.");
    }
    const notices = new Map<string, PackageNotice>();
    for (const built of Object.values(result.metafile.outputs)) {
      if (built.imports.length !== 0) throw new Error("Markdown parser bundle has external imports");
      for (const [input, contribution] of Object.entries(built.inputs)) {
        if (contribution.bytesInOutput === 0) continue;
        let directory = dirname(resolve(ROOT, input));
        if (directory === scratch) continue;
        while (!existsSync(join(directory, "package.json"))) {
          const parent = dirname(directory);
          if (parent === directory) throw new Error(`No package.json for bundled input ${input}`);
          directory = parent;
        }
        const pkg = JSON.parse(readFileSync(join(directory, "package.json"), "utf8"));
        const key = `${pkg.name}@${pkg.version}`;
        if (notices.has(key)) continue;
        if (pkg.license !== "MIT") throw new Error(`Unexpected bundled license for ${key}: ${pkg.license}`);
        const license = readdirSync(directory).sort().find((name) => /^licen[cs]e(?:\.md|\.txt)?$/i.test(name));
        if (!license) throw new Error(`Missing MIT notice for ${key}`);
        const text = readFileSync(join(directory, license), "utf8");
        if (text.includes("*/")) throw new Error(`Cannot embed license comment for ${key}`);
        notices.set(key, { name: pkg.name, version: pkg.version, license: pkg.license, text });
      }
    }
    const packages = [...notices.values()].sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0);
    for (const name of ["micromark", "micromark-extension-gfm", "micromark-util-normalize-identifier"]) {
      const pkg = packages.find((notice) => notice.name === name);
      if (!pkg || rootPackage.devDependencies[name] !== pkg.version) {
        throw new Error(`Bundled ${name} must match its exact devDependency pin`);
      }
    }
    const header = [
      "/*",
      "Generated by scripts/vendor-markdown-parser.ts — do not edit.",
      `Bun ${MARKDOWN_PARSER_BUN_VERSION}; target=bun; format=esm; minify=true`,
      "",
      ...packages.flatMap((pkg) => [`${pkg.name}@${pkg.version} (${pkg.license})\n${pkg.text}`, ""]),
      "*/",
      "",
    ].join("\n");
    mkdirSync(dirname(output), { recursive: true });
    writeFileSync(output, header + await result.outputs[0].text());
  } finally {
    rmSync(scratch, { recursive: true, force: true });
  }
}

if (import.meta.main) {
  const args = process.argv.slice(2);
  if (args.length !== 0 && (args.length !== 2 || args[0] !== "--output")) {
    throw new Error("Usage: bun scripts/vendor-markdown-parser.ts [--output <path>]");
  }
  await vendorMarkdownParser(args[1] ? resolve(args[1]) : undefined);
}
